export const HELP_LINES = [
  'j/k     move selection',
  'h       parent directory',
  'l/Enter open / enter dir',
  'Space   toggle mark',
  'a       select all',
  'u/Esc   clear marks',
  'y       yank (copy)',
  'x       cut',
  'p       paste',
  'd       delete (trash)',
  'D       delete permanently',
  'r       refresh',
  '.       hidden files',
  's       cycle sort',
  'S       toggle sort direction',
  'f       filter',
  'g/G     top / bottom',
  ':/!     path / shell command',
  'm/\'     bookmark / go bookmark',
  'H/L     back / forward history',
  'o       open file',
  'n/N     new dir / new file',
  'F2      rename',
  'P       preview toggle',
  '?       help',
  'q       quit',
]
